server:
  port: 8081

spring:
  application:
    name: cloud-gateway
  consul:
    consul:
      host: localhost
      port: 8500
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: routh #路由的ID，没有固定规则但要求唯一
          uri: lb://spring-cloud-consul-provider   #匹配后提供服务的路由地址
          predicates:
            - Path=/provider/serviceProvider/**   #断言,路径相匹配的进行路由

